version: '3'
services:

  node:

    image: node:10.15.0
    container_name: covid_community_node
    volumes:
      - ${PWD}/:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: bash -c "npm install && npm run start"
